use APTITUDE_TEST;

CREATE TABLE ComputerTest (
    ID INT PRIMARY KEY IDENTITY(1,1),
    Question VARCHAR(MAX),
    OptionA VARCHAR(255),
    OptionB VARCHAR(255),
    OptionC VARCHAR(255),
    OptionD VARCHAR(255),
    CorrectAnswer VARCHAR(1)
);

CREATE TABLE GKTest (
    ID INT PRIMARY KEY IDENTITY(1,1),
    Question VARCHAR(MAX),
    OptionA VARCHAR(255),
    OptionB VARCHAR(255),
    OptionC VARCHAR(255),
    OptionD VARCHAR(255),
    CorrectAnswer VARCHAR(1)
);

CREATE TABLE MathTest (
    ID INT PRIMARY KEY IDENTITY(1,1),
    Question VARCHAR(MAX),
    OptionA VARCHAR(255),
    OptionB VARCHAR(255),
    OptionC VARCHAR(255),
    OptionD VARCHAR(255),
    CorrectAnswer VARCHAR(1)
);

CREATE TABLE FINALRESULTS (
    F_ID INT PRIMARY KEY IDENTITY(1,1),
    F_TOTALSCORE_GK INT NOT NULL,
    F_TOTALSCORE_MATHS INT NOT NULL,
    F_TOTALSCORE_COMPUTER INT NOT NULL,
    F_PERCENTAGE DECIMAL(5, 2) NOT NULL,
    F_USERSTATUS VARCHAR(50) NOT NULL,
	F_TESTDATE DATETIME DEFAULT GETDATE(),
    F_JA_ID INT,
    FOREIGN KEY (F_JA_ID) REFERENCES JobApplication(J_ID),
	F_USER_ID INT, 
    FOREIGN KEY (F_USER_ID) REFERENCES USERS(USER_ID),
	 F_TOTALMARKS_GK INT ,
    FOREIGN KEY (F_TOTALMARKS_GK) REFERENCES GKTest(ID),
    F_TOTALMARKS_MATHS INT , 
	FOREIGN KEY (F_TOTALMARKS_MATHS) REFERENCES MathTest(ID),
    F_TOTALMARKS_COMPUTER INT,
	FOREIGN KEY (F_TOTALMARKS_COMPUTER) REFERENCES ComputerTest(ID),
);

CREATE TABLE JobApplication (
    J_ID INT PRIMARY KEY IDENTITY(1,1),
    J_FULLNAME VARCHAR(100) NOT NULL, 
    J_EMAIL VARCHAR(100) UNIQUE NOT NULL,
    J_PHONE VARCHAR(20) NOT NULL,
    USER_ADDRESS VARCHAR(255) NOT NULL,
    J_RESUME VARCHAR(255) NOT NULL,
    J_MESSAGE TEXT NOT NULL,
    J_SUBMISSION DATETIME DEFAULT GETDATE(),
		J_USER_ID INT, 
    FOREIGN KEY (J_USER_ID) REFERENCES USERS(USER_ID) 
);



  CREATE TABLE Jobs (
    JobId INT PRIMARY KEY IDENTITY(1,1),
    JobTitle VARCHAR(100),
    CompanyName VARCHAR(100),
    JobLocation VARCHAR(100),
    EmploymentType VARCHAR(50)
);

  CREATE TABLE Candidates (
    CandidateID INT PRIMARY KEY IDENTITY(1,1),
    FullName VARCHAR(100) NOT NULL,
    ImageURL VARCHAR(255),
	Cant_Description Text,
    Location VARCHAR(100),
    CreatedDate DATETIME DEFAULT GETDATE()
);


CREATE TABLE Role(
Role_Id INT PRIMARY KEY IDENTITY(1,1),
Role_Name VARCHAR(255) NOT NULL
);


CREATE TABLE USERS(
    USER_ID INT PRIMARY KEY IDENTITY(1,1),
    USER_NAME VARCHAR(75) NOT NULL,
    USER_EMAIL VARCHAR(255) UNIQUE NOT NULL,
    USER_PASSWORD VARCHAR(255) NOT NULL, 
    USER_IMAGE VARCHAR(255),
    USER_ROLE_ID INT, 
    FOREIGN KEY (USER_ROLE_ID) REFERENCES Role(ROLE_ID) 
);


CREATE TABLE CONTACT(
CONT_ID INT PRIMARY KEY IDENTITY(1,1),
CONT_NAME VARCHAR(255) NOT NULL,
CONT_EMAIL VARCHAR(255) NOT NULL ,
CONT_PHONE VARCHAR(20) NOT NULL ,
CONT_ADDRESS VARCHAR(255) NOT NULL,
CONT_MESSAGE TEXT ,
CREATED_AT DATETIME DEFAULT GETDATE()
);






select * from FinalResults


select * from JobApplications



	